### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by tenleftfingers** [joernweissenborn/lcars#12]
Not an issue, but a thanks for making this. I was able to add some basic animation to make important buttons pulseate and animate list items. Just the beginning of a small personal project https://www.youtube.com/watch?v=FW3wi8TL8_s&feature=youtu.be

**Comment by joernweissenborn** [comment]
Thanks for showing that to me @tenleftfingers 

It is one best feelings to see that your work helps other to create cool stuff! If you have any troubles, just write an issue, I am happy to assist.

**Comment by tenleftfingers** [comment]
Thanks @joernweissenborn, and also thanks for the responses to my other question! I'll experiment with that information and come back. Much appreciated.

**Comment by joernweissenborn** [comment]
Welcome ;)
