### ISSUE TITLE
Call for collaborators

### ISSUE THREAD

**Issue by joernweissenborn** [joernweissenborn/lcars#16]
Hi everybody, I can really use some hands to maintain this in the future, so I am looking for people helping me to keep this project alive and usable.

There is alot of things to do (most importantly fix and extend documentation/examples), answer questions and so on, which I unfortunately don't have much time for. At least not not as much as I want. So if somebody has time to help, just reply to this issue!

**Comment by tenleftfingers** [comment]
I was about to post an issue/question when I saw this :) I will help in any way I can. But, things are a little unpredictable at present and I cannot say how much time I will have from month to month.

**Comment by joernweissenborn** [comment]
Hi, thank you for much for the answer and your offer to help!

All of this are cool ideas. Please open up separate issues for all of them so we then discuss it in detail.

So my next would be:

* overhole current example
* make/link more examples
* ask what other people would like and find time to implement :)

That is my rough plan. This shall be a community driven project, so besides this it is up to your guys what happens next. Sky is the limit... :D

**Comment by joernweissenborn** [comment]
@tenleftfingers You should be able to find my mail address here https://github.com/glotaran/pyglotaran. Please write me an E-Mail!

**Comment by joernweissenborn** [comment]
I think we have enough collaborators and issues for advancement so this issue can be closed.

Thank you guys for joining this project and working on it!
