### ISSUE TITLE
Replacement or notes on replacement sound effects that are more authentic

### ISSUE THREAD

**Issue by jrwarwick** [joernweissenborn/lcars#24]
Previously, audio support was added and some totally inauthentic cheesy place holder sounds effects were included. I have gotten permission from The current owner of STdimension to use the collection of sfx, including renaming files, and distributing. He noted that it would be advisable to review liability, and to include disclaimer and attribution to CBS/Paramount if we do it. I'm in favor of this; it's not commerical, very minor sample and precedent exists for reuse.

If we don't do this, I could instead provide simple instructions, maybe even a script to "upgrade" the sounds to the authentic editions.

What do you think?

**Comment by joernweissenborn** [comment]
I would say we should get sounds inside out and leave it to the users to provide sounds! Can you make a PR for that?

**Comment by joernweissenborn** [comment]
The reason is, besides that we could get trouble providing original sound, it blows up the repository (audio and git don't like each other). But I am open for reasons to have some "cheese" placeholders in.

**Comment by jrwarwick** [comment]
I understand, I will make a deletion PR. The place holders would only have
value to make the gh-pages demo easier to manage, with full capability
demonstrated.

  --Justin

**Comment by joernweissenborn** [comment]
I leave it to your judgment if your sounds could make copyright issues, but if you made them yourself there should be no issues and we could keep a few in for demo. In the end, people will not use the wholl repo but only the min.css

**Comment by jrwarwick** [comment]
Right, good point. Ok I will just leave in the few place holders for the
easy demo. As you say, no threat since I just created them from scratch.
Maybe I will just add a quick note about the renaming and the sites that
might be good sources for users to collect from. Would be ok?

  --Justin

**Comment by joernweissenborn** [comment]
Perfect. A link should not hurt so fine with me.

Am So., 17. Nov. 2019 um 00:54 Uhr schrieb Justin Warwick <
notifications@github.com>:
