### ISSUE TITLE
Support for Special Elements with complex geometry

### ISSUE THREAD

**Issue by jrwarwick** [joernweissenborn/lcars#26]
Some elements with complex geometry will be difficult to achieve with "pure" CSS, yet are really iconic in the LCARS/okudagram style. For instance, the classic circular X/Y control found on many consoles including the helm.
I have found that although less well widely known, the SVG support in browsers is really pretty good these days. This may be a nice way to meet this need, and it can be done in a very modular/optional way.

**Comment by joernweissenborn** [comment]
Totally right. SVG is the path to go here. The only thing is tht people
want to have nice event options so one can link it it to whateverJS.

I guess it would be nice to have some iconic demo SVGs included, together
with interactive demo.

Am Mo., 18. Nov. 2019 um 23:09 Uhr schrieb Justin Warwick <
notifications@github.com>:
