### ISSUE TITLE
Gulpfile configured for older version

### ISSUE THREAD

**Issue by xenziffen** [joernweissenborn/lcars#43]
The current `gulpfile.js` file is written for Gulp v3 while Gulp v4 is available. The package manager reminds me there is an update, and in my environment I end up switching between gulp3 and gulp4.

Moving to the new version of Gulp requires designating the default tasks with `serial` or `parallel` for calling the list of tasks. And providing a callback parameter `done` that can be called at the end of each task.

I'll create a branch with those changes so we can discuss updating.

**Comment by jrwarwick** [comment]
thanks for the upgrade, I struggled (as usual, I am just not "native" in node land ) to get the local bit upgraded but it is all merged in now.
