### ISSUE TITLE
Short filenames

### ISSUE THREAD

**Issue by physnoct** [joernweissenborn/lcars#47]
I'm using LCARS on an embedded platform (ESP32-CAM). The embedded website files are on a SD cards but the firmware uses common DOS 8.3 filenames.
LCARS works on it when using DOS filenames.

**Comment by joernweissenborn** [comment]
Hi @physnoct 

I am happy to see that LCARS works on embedded (never tried but sure intended to), but I fail to see an issue here. The CSS file is generated from stylus files and is self-consistent. Thus you are free to rename it to a shorter (DOS-Compatible) name and adapt the import in your HTML. 

Does this info help you?

**Comment by jrwarwick** [comment]
I agree with Joern on this one. But if you wanted to create some special-case build rules in a separate gulp job definition file that would generate 8.3-compliant filenames, I think we could find a way to include that, as long as it tests out ok and runs without error. I will close for now, but I can reopen if you decide you want to create a PR for that.
