### ISSUE TITLE
New Owner

### ISSUE THREAD

**Issue by joernweissenborn** [joernweissenborn/lcars#5]
You stated that the package would need a new owner. I wanted to write my own LCARS CSS and would be interested at just continue your work.

I haven't worked with Stylus so far, but I am willing to learn. I will see if can setup everything tomorrow. If you could drop a few hints about the structure it would be helpful!

**Comment by Garrett-** [comment]
It seems you have already forked this repository. For me to be able to transfer ownership to you you'll need to delete the fork. Let me know when that's done. Once it's yours you can do as you please you don't need to stick with Stylus.

**Comment by joernweissenborn** [comment]
I deleted the fork.

**Comment by Garrett-** [comment]
It's yours

**Comment by joernweissenborn** [comment]
Thanks for your work!
