### ISSUE TITLE
Creating a menu?

### ISSUE THREAD

**Issue by picardrulez** [joernweissenborn/lcars#7]
This could just be my lack of css knowledge, but do you have any examples of using the button elements along the left side menu bar?

Also, I've been using your lcars css template for my golang apps and this weekend started turning it into a go library incorporating it into the usual web framework I use.  I hope you don't mind:  www.github.com/picardrulez/lcars

**Comment by picardrulez** [comment]
I figured out the menu, thanks anyway!

**Comment by picardrulez** [comment]
Actually, I could probably use a little help.  This is what I came up with for adding menu buttons to the left hand menu (based off of your example html).  I tried having it match your buttons example but for some reason the buttons are overlapping instead of having a space (I'm trying to get a space the same size as the the space between the bend at the top and the menu filler.  I tried adding a </br> after each button but that just made a black space 3 or 4 times too wide.  Here's the code I'm currently using:

        

        <div id="left-menu" class="lcars-column start-space lcars-u-1">
                        <div class="lcars-column">
                                <div class="lcars-row">
                                        <div class="lcars-element button lcars-blue-bell-bg">Settings</div>
                                </div>
                                <div class="lcars-row">
                                        <div class="lcars-element button lcars-hopbush-bg">Users</div>
                                </div>
                                <div class="lcars-row">
                                        <div class="lcars-element button lcars-pale-canary-bg">Info</div>
                                </div>
                                <div class="lcars-row">
                                        <div class="lcars-element button lcars-blue-bell-bg">About</div>
                                </div>
                        </div>

          
          <div class="lcars-bar lcars-u-1"></div>
        </div>

**Comment by picardrulez** [comment]
Figured it out!  I did the opposite similar to how you did your section showing the colors:  swtiched the column and row around and removed all of those rows in between each element.

**Comment by joernweissenborn** [comment]
I am happy you could solve your problem! Sorry for not responding earlier, I forgot to put notifications on :)

Feel free to ask if you have further problems! I would love some feedback and maybe see what people are doing with it.
