### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by joernweissenborn** [joernweissenborn/lcars#8]
It would be nice if user could just download a zip with css instead of cloning the entire repo.

**Comment by sfranzyshen** [comment]
> It would be nice if user could just download a zip with css instead of cloning the entire repo.

I have also been playing around with alternatives to cloning the entire repo ... have a look
[alternate-deployment-models](https://sfranzyshen.github.io/LCARS-SDK-ARCHIVE/#alternate-deployment-models)

**Comment by joernweissenborn** [comment]
Since I got a enough feedback and the project seams to really found users, I am to make more examples, tweak everything a little, I and make a `1.0` release within in this year. I will continue to maintain the library after that.

Feedback is very much appreciated, please issue tracker!

Thanks for your interest, it is really motivating!

**Comment by jrwarwick** [comment]
https://github.com/joernweissenborn/lcars/releases/tag/v1.0.0-beta
