### ISSUE TITLE
Add link to repo from demo

### ISSUE THREAD

**Issue by MrOnosa** [joernweissenborn/lcars#9]
Google took me to http://joernweissenborn.github.io/lcars/, but it doesn't have a link to https://github.com/joernweissenborn/lcars

**Comment by MrOnosa** [comment]
Also I'd love to show you how I used this to make something cool. I couldn't find a twitter or any way to contact you.

**Comment by joernweissenborn** [comment]
Hi, Sorry for the late reply. I would really love to see what you did with it! 

Thanks for the hint with the link, I will add one.

**Comment by MrOnosa** [comment]
[Here it is](https://mronosa.keybase.pub/lcars.mp4)!
